#new
#LP 4.035
#X 1 0 0
#Y 0 1 0
#Z 0 0 1
#CC 5 5 5 
#RC 6.5                
#F N         
#BM 76 GPA
#EC 3 114 61 31 GPA 
#EV 8100.0 ANG3
Al 0 0 0
Al 0.5 0.5 0
Al 0.5 0 0.5
Al 0 0.5 0.5
#end
#new
#LP 4.2789
#X 1 0 0
#Y 0 1 0
#Z 0 0 1
#CC 5 5 5 
#EPA -3.256 eV
#RC 6.5        
#EC 3 114 61 31 GPA         
#F N           
Al 0 0 0
Al 0.5 0.5 0
Al 0.5 0 0.5
Al 0 0.5 0.5
#end
#new
#LP 3.95597
#X 1 0 0
#Y 0 1 0
#Z 0 0 1
#CC 5 5 5 
#EPA -3.344 eV
#RC 6.5         
#BM 80 GPA       
#F N           
#EV 8100.0 ANG3
Al 0 0 0
Al 0.5 0.5 0
Al 0.5 0 0.5
Al 0 0.5 0.5
#end